# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
#
# http://docs.travis-ci.com/user/customizing-the-build/
# http://lint.travis-ci.org/

os: linux
dist: trusty
sudo: required
services: docker
language: c
matrix:
  fast_finish: true

env:
  global:
    #- http_proxy="http://example.com"
    - bintray_url="https://dl.bintray.com/beast-team"
  matrix:
    - XFROM="ubuntu:wily"   XUP="wily"

before_install:
  - uname -a
  - cat /etc/os-release
  - pwd
  - free -tm
  - make --version
  - python --version
  - $CC --version

install:
  # Complete history is required for VCSREVISION
  - travis_retry git fetch --unshallow
  # Configure Dockerfile by substituting @VAR@ with $VAR
  - export RAPICORNREPO="$bintray_url/$XUP snapshot main" &&
    ./buildtool.sh applyenv .travis.docker > Dockerfile
  # Build and run tests, create packages
  - docker build -t beast .

script:
  # Upload packages
  - test -z "$XUP" || docker run -ti --rm beast /bin/bash -c
    "export BINTRAY_APITOKEN=$BINTRAY_APITOKEN && ls -al && beast/buildtool.sh bintrayup beast-team $XUP/beast snapshot *.deb"
  - docker ps -a

after_success:
  - echo "Done, all OK!"

notifications:
  irc:
    channels:
      - "irc.gimp.org#beast"
    on_success: change # always / never / change
    on_failure: change # always / never / change
    skip_join: true
  email: false
    #recipients:
    #  - beast@gnome.org
    #on_success: change
    #on_failure: change
